openapi: 3.1.0
info:
  version: 1.0.0
  title: E-Pharmacy app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of E-Pharmacy app
tags:
  - name: Customers
    description: Operations about customers.
  - name: Products
    description: Operations about products.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /customers:
    get:
      $ref: ../swagger/paths/customers/get.yaml
  /customers/{id}:
    get:
      $ref: ../swagger/paths/customers/{id}/get.yaml
  /products:
    post:
      $ref: ../swagger/paths/products/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
